# This file is machine-generated - editing it directly is not advised

[[OffsetArrays]]
git-tree-sha1 = "ab697473e983a7499f463b696da8e8feb1b20ffd"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.1.0"
