# This file is machine-generated - editing it directly is not advised

[[OffsetArrays]]
git-tree-sha1 = "663d3402efa943c95f4736fa7b462e9dd97be1a9"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.2.0"
